/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.1/samples
 */
plugins {
    java
}

subprojects {
    apply(plugin = "java") // Forces every sub-folder to be treated as a Java project.
    repositories {
        mavenCentral() // Look for imported libraries on Maeven Central 
    }
}

// Server project
project(":server") {
    // The server depends on common function/classees in the ":common" project
    dependencies { 
        implementation(project(":common"))
    }

    // apply(plugin = "application")

    // application {
    //     mainClass.set("os.chat.server.ChatClientWindow")
    // }
}

// Client project
project(":client") {
    dependencies {
        implementation(project(":common"))
    }

    apply(plugin = "application") // adds the :run task to the project (since it is an application)
    // Set the Main class to the ChatClientWindow class (which has a main function)
    configure<JavaApplication> { 
        mainClass.set("os.chat.client.ChatClientWindow")
        applicationDefaultJvmArgs = listOf("-Dsun.java2d.uiScale=2") // Fix scaling
    }
}

project(":common") {
    // Common code between the two projects
}